# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://landing.pbn.my.id
title: FB Auto Share
email: admin@pbn.my.id
author: mBurokz
description: Landing page blog PBN yang dibuat dengan Jekyll dan hosting Github
copyright: 'Copyright &copy; 2022 mBurokz Dev. All Rights Reserved.'
credits: 'Credits: Landing Page ini dibuat untuk blog <a href="https://www.pbn.my.id/">PBN</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
plugin: 
- jekyll-seo-tag

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/sajakrerindu
  - title: github
    url: https://github.com/mburokz
  - title: facebook
    url: https://www.facebook.com/mburokz
